(define (problem block-grouping)
(:domain block-grouping)
(:objects 
	b0 - block
	b1 - block
	b2 - block
	b3 - block
	b4 - block
	b5 - block
	b6 - block
	b7 - block
)
(:init
	(= (x b0) 20)
	(= (y b0) 9)
	(= (x b1) 12)
	(= (y b1) 17)
	(= (x b2) 1)
	(= (y b2) 15)
	(= (x b3) 8)
	(= (y b3) 2)
	(= (x b4) 6)
	(= (y b4) 4)
	(= (x b5) 12)
	(= (y b5) 16)
	(= (x b6) 8)
	(= (y b6) 13)
	(= (x b7) 18)
	(= (y b7) 4)
	(= (max_x) 20)
	(= (min_x) 0)
	(= (max_y) 20)
	(= (min_y) 0)
	(= (lower_bound) 0)
	(= (upper_bound) 19)
	(= (delta) 0)
)
(:goal (and
	(or (not (= (x b0) (x b1))) (not (= (y b0) (y b1))))
	(or (not (= (x b0) (x b2))) (not (= (y b0) (y b2))))
	(or (not (= (x b0) (x b3))) (not (= (y b0) (y b3))))
	(or (not (= (x b0) (x b4))) (not (= (y b0) (y b4))))
	(or (not (= (x b0) (x b5))) (not (= (y b0) (y b5))))
	(or (not (= (x b0) (x b6))) (not (= (y b0) (y b6))))
	(or (not (= (x b0) (x b7))) (not (= (y b0) (y b7))))
	(or (not (= (x b1) (x b2))) (not (= (y b1) (y b2))))
	(or (not (= (x b1) (x b3))) (not (= (y b1) (y b3))))
	(or (not (= (x b1) (x b4))) (not (= (y b1) (y b4))))
	(or (not (= (x b1) (x b5))) (not (= (y b1) (y b5))))
	(or (not (= (x b1) (x b6))) (not (= (y b1) (y b6))))
	(= (x b1) (x b7))
	(= (y b1) (y b7))
	(or (not (= (x b2) (x b3))) (not (= (y b2) (y b3))))
	(= (x b2) (x b4))
	(= (y b2) (y b4))
	(or (not (= (x b2) (x b5))) (not (= (y b2) (y b5))))
	(or (not (= (x b2) (x b6))) (not (= (y b2) (y b6))))
	(or (not (= (x b2) (x b7))) (not (= (y b2) (y b7))))
	(or (not (= (x b3) (x b4))) (not (= (y b3) (y b4))))
	(= (x b3) (x b5))
	(= (y b3) (y b5))
	(= (x b3) (x b6))
	(= (y b3) (y b6))
	(or (not (= (x b3) (x b7))) (not (= (y b3) (y b7))))
	(or (not (= (x b4) (x b5))) (not (= (y b4) (y b5))))
	(or (not (= (x b4) (x b6))) (not (= (y b4) (y b6))))
	(or (not (= (x b4) (x b7))) (not (= (y b4) (y b7))))
	(= (x b5) (x b6))
	(= (y b5) (y b6))
	(or (not (= (x b5) (x b7))) (not (= (y b5) (y b7))))
	(or (not (= (x b6) (x b7))) (not (= (y b6) (y b7))))
))
)

