(define (problem disc_drone)
(:domain disc_drone)
(:objects 
	loc0 - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
)
(:init
	(= (x) 0)
	(= (y) 0)
	(= (z) 0)
	(= (min_x) 0)
	(= (min_y) 0)
	(= (min_z) 0)
	(= (max_x) 3)
	(= (max_y) 3)
	(= (max_z) 3)
	(= (xl loc0) 3)
	(= (yl loc0) 3)
	(= (zl loc0) 1)
	(= (xl loc1) 0)
	(= (yl loc1) 3)
	(= (zl loc1) 0)
	(= (xl loc2) 0)
	(= (yl loc2) 3)
	(= (zl loc2) 3)
	(= (xl loc3) 3)
	(= (yl loc3) 3)
	(= (zl loc3) 0)
	(= (xl loc4) 1)
	(= (yl loc4) 0)
	(= (zl loc4) 2)
	(= (battery-level) 47)
	(= (battery-level-full) 47)
	(= (low_deltax) 1)
	(= (low_deltay) 1)
	(= (low_deltaz) 1)
	(= (deltax) 1)
	(= (deltay) 1)
	(= (deltaz) 1)
	(= (up_deltax) 3)
	(= (up_deltay) 3)
	(= (up_deltaz) 3)
)
(:goal (and
	(visited loc0)
	(visited loc1)
	(visited loc2)
	(visited loc3)
	(visited loc4)
	(= (x) 0)
	(= (y) 0)
	(= (z) 0)
))
)

