(define (problem disc_drone)
(:domain disc_drone)
(:objects 
	loc0 - location
	loc1 - location
	loc2 - location
	loc3 - location
	loc4 - location
	loc5 - location
	loc6 - location
	loc7 - location
	loc8 - location
	loc9 - location
)
(:init
	(= (x) 0)
	(= (y) 0)
	(= (z) 0)
	(= (min_x) 0)
	(= (min_y) 0)
	(= (min_z) 0)
	(= (max_x) 4)
	(= (max_y) 4)
	(= (max_z) 4)
	(= (xl loc0) 0)
	(= (yl loc0) 0)
	(= (zl loc0) 4)
	(= (xl loc1) 0)
	(= (yl loc1) 3)
	(= (zl loc1) 1)
	(= (xl loc2) 0)
	(= (yl loc2) 2)
	(= (zl loc2) 0)
	(= (xl loc3) 1)
	(= (yl loc3) 4)
	(= (zl loc3) 0)
	(= (xl loc4) 3)
	(= (yl loc4) 3)
	(= (zl loc4) 3)
	(= (xl loc5) 0)
	(= (yl loc5) 3)
	(= (zl loc5) 3)
	(= (xl loc6) 4)
	(= (yl loc6) 0)
	(= (zl loc6) 3)
	(= (xl loc7) 1)
	(= (yl loc7) 0)
	(= (zl loc7) 3)
	(= (xl loc8) 2)
	(= (yl loc8) 0)
	(= (zl loc8) 3)
	(= (xl loc9) 2)
	(= (yl loc9) 1)
	(= (zl loc9) 4)
	(= (battery-level) 47)
	(= (battery-level-full) 47)
	(= (low_deltax) 1)
	(= (low_deltay) 1)
	(= (low_deltaz) 1)
	(= (deltax) 1)
	(= (deltay) 1)
	(= (deltaz) 1)
	(= (up_deltax) 4)
	(= (up_deltay) 4)
	(= (up_deltaz) 4)
)
(:goal (and
	(visited loc0)
	(visited loc1)
	(visited loc2)
	(visited loc3)
	(visited loc4)
	(visited loc5)
	(visited loc6)
	(visited loc7)
	(visited loc8)
	(visited loc9)
	(= (x) 0)
	(= (y) 0)
	(= (z) 0)
))
)

